##### local
POST http://localhost:3000/api/revalidar HTTP/1.1
content-type: application/json

{
    "secret": "puto_el_que_lee",
    "path": "/",
    "tags": ["precios-mercado", "categorias", "unidades"]
}

##### test
POST https://agro.tisoler.net.ar/api/revalidar HTTP/1.1
content-type: application/json

{
    "secret": "puto_el_que_lee",
    "path": "/",
    "tags": ["precios-mercado", "categorias", "unidades"]
}

##### prod
POST https://fabiotommasi.com.ar/api/revalidar HTTP/1.1
content-type: application/json

{
    "secret": "puto_el_que_lee",
    "tags": ["precios-mercado", "categorias", "unidades"]
}
